# Generated by Django 2.2.4 on 2019-08-11 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('publication_date', models.DateField(default=datetime.datetime(2019, 8, 11, 18, 26, 17, 73014, tzinfo=utc))),
            ],
        ),
    ]
